import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google'
const openSans = Inter({
  weight: "400",
  subsets: ["latin"],
  display: 'swap',
  style: ["normal"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
      // className={openSans.className}
      >
        {children}
      </body>
    </html>
  );
}
